### PR TITLE
Hotfix/3/SC-7804 - rename index to avoid collision with page

### PR DESCRIPTION
**Pull request by pkleybolte**
# Description

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7804

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Review by CeEv — APPROVED** [review]

**Comment by mamutmk5** [comment]
@schul-cloud-bot update screenshots

**Comment by mamutmk5** [comment]
@schul-cloud-bot update screenshots

**Comment by mamutmk5** [comment]
@hpi-schul-cloud-bot update screenshots

**Comment by mamutmk5** [comment]
@hpi-schul-cloud-bot update screenshots

**Comment by mamutmk5** [comment]
@schul-cloud-bot update screenshots

**Comment by mamutmk5** [comment]
@schul-cloud-bot update screenshots

**Comment by virgilchiriac** [comment]
@schul-cloud-bot update screenshots

**Comment by virgilchiriac** [comment]
@schul-cloud-bot update screenshots

**Comment by virgilchiriac** [comment]
@hpi-schul-cloud-bot update screenshots

**Pull request merged**
