### PR TITLE
Quickfix - news not published later

### PR DESCRIPTION
**Pull request by BlackGhostHD**
# Description

## Links to Tickets or other pull requests

https://github.com/hpi-schul-cloud/integration-tests/pull/109
https://ticketsystem.schul-cloud.org/browse/SC-5758

## Screenshots of UI changes
Opera Momentaufnahme_2020-07-27_123154_localhost

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by BlackGhostHD** [comment]
@schul-cloud-bot update screenshots

**Comment by janrenz** [comment]
I guess the content should be filtered on the server, or is this a differnetn issue?

**Comment by BlackGhostHD** [comment]
@janrenz No, the problem is that if you create a new news item and only specify a publishing day but no time, it will be published directly. Now if you only set a day, the time is automatically set to 00:00.

**Comment by BlackGhostHD** [comment]
@schul-cloud-bot update screenshots

**Pull request merged**
