### PR TITLE
Hotfix/1/SC-6932 - Add missing translations to sidebar in nuxt client

### PR DESCRIPTION
**Pull request by ABialoskorski**
# Description
merge hotfix - https://github.com/hpi-schul-cloud/nuxt-client/pull/1376 to develop

### CODE REVIEW

**Comment by ABialoskorski** [comment]
@schul-cloud-bot update screenshots

**Comment by ABialoskorski** [comment]
@schul-cloud-bot update screenshots

**Comment by ABialoskorski** [comment]
@schul-cloud-bot update screenshots

**Comment by ABialoskorski** [comment]
@schul-cloud-bot update screenshots

**Review by DanielRieckhof — APPROVED** [review]

**Pull request closed without merging**
