### PR TITLE
Hotfix/5/SC-7447 - leave text

### PR DESCRIPTION
**Pull request by JenyMzo**
# Description
Conditional rendering of information when logged in through brandenburg
Hotfix. more info coming

### CODE REVIEW

**Comment by JenyMzo** [comment]
@schul-cloud-bot update screenshots

**Review by virgilchiriac — APPROVED** [review]

**Comment by JenyMzo** [comment]
@schul-cloud-bot update screenshots

**Comment by DanielRieckhof** [comment]
@schul-cloud-bot update screenshots

**Comment by JenyMzo** [comment]
@Mergifyio refresh

**Pull request merged**
