### PR TITLE
SC-8518 - layout issues with checkboxes and labels in filters and registration

### PR DESCRIPTION
**Pull request by pauljanns**
# Description
New Admin Tables Fix! - There were minor layout bugs due to a weird set margin on the checkbox label. I fixed it by setting margin-top to 0 and not -12

## Links to Tickets or other pull requests
- https://ticketsystem.schul-cloud.org/browse/SC-8518

## Changes
fixed layout bug in NAT

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by pauljanns** [comment]
@schul-cloud-bot update screenshots

**Review by dominikbruechner — CHANGES_REQUESTED** [review]
Please check the Screenshot Tests, you have side-effects in the switch component:
Screenshot 2021-03-30 at 11 43 51

**Review by j-jmnz — CHANGES_REQUESTED** [review]
Please add a changelog entry :)

**Comment by dominikbruechner** [comment]
@schul-cloud-bot update screenshots

**Comment by dominikbruechner** [comment]
Screenshot tests are good for now. after adding release notes, this one can be approved

**Pull request merged**
